apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: home
  namespace: monitoring
spec:
  additionalArgs:
    memory.allowedPercent: "40"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: In
            values:
            - "true"
  arbitraryFSAccessThroughSMs: {}
  externalLabels:
    cluster: home
  image:
    pullPolicy: Always
    repository: victoriametrics/vmagent
    tag: v1.59.0
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  remoteWrite:
  - url: http://vminsert-home.monitoring.svc.cluster.local:8480/insert/100/prometheus/api/v1/write
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 850Mi
    requests:
      cpu: 250m
      memory: 350Mi
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vmagent
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vmagent-192-168-1-242.nip.io`)
      kind: Rule
      services:
        - name: vmagent-home
          port: 8429
