apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-system-controller-manager-alerts
  namespace: monitoring
spec:
  groups:
  - "name": "kubernetes-system-controller-manager"
    "rules":
    - "alert": "KubeControllerManagerDown"
      "annotations":
        "description": "KubeControllerManager has disappeared from Prometheus target discovery."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown"
        "summary": "Target disappeared from Prometheus target discovery."
      "expr": |
        absent(up{job="k3s-server"} == 1)
      "for": "15m"
      "labels":
        "severity": "critical"
