apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    port: metrics
  jobLabel: jobLabel
  namespaceSelector: {}
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: node-exporter

